### ISSUE TITLE
Show connected wallet info 

### ISSUE THREAD

**Issue by edakturk14** [BuidlGuidl/batch4.buidlguidl.com#4]
## Goal

When a user connects to the dApp, let's display 2 things:

1. Is the connected address a member of the batch? (is the in the allowList)
2. Is the connected address already checked in?

Feel free to place that info whenever you want. It could be just some icons that show next to the wallet for members.

For more info about the contract: [Check-in with the BatchRegistry contract](https://github.com/BuidlGuidl/batch4.buidlguidl.com/issues/9)

**Comment by yashgo0018** [comment]
I am starting the work on this one.
