### ISSUE TITLE
Change the Logo / title / subtitle

### ISSUE THREAD

**Issue by edakturk14** [BuidlGuidl/batch4.buidlguidl.com#7]
## Goal

Update your batch's mainpage. 

![284656861-52a77020-0c08-4136-8cc5-244bc3bd088a](https://github.com/BuidlGuidl/batch2.buidlguidl.com/assets/2486142/f9d3495a-9946-4b8e-ac55-8e00cdc380e0)

- Create a random logo (or use Dall-E!) to generate a batch logo
- title: Batch #{batch_number}
- subtitle: Whatever you feel appropriate :)

**Comment by BillSchumacher** [comment]
I suck at logos and pretty but here's what ChatGPT came up with:
![image](https://github.com/BuidlGuidl/batch4.buidlguidl.com/assets/34168009/f2bf3c87-ebaa-4f9e-807d-4664bfbf217c)

**Comment by bhavyagor12** [comment]
@BillSchumacher hey, I really like that logo. Honestly shows true buidler power 🦾

**Comment by Welith** [comment]
The logo seems legit to me as well!

**Comment by bhavyagor12** [comment]
@BillSchumacher are you gonna pick this up and get our batch a customized logo? let me know if you need any help!!

**Comment by BillSchumacher** [comment]
I can after work, if someone else wants to implement feel free.

**Comment by BillSchumacher** [comment]
Could use a bit more love

**Comment by gugasanchez** [comment]
Amazing logo @BillSchumacher! Liked it a lot!

Did you already made changes in the frontend to include it? I can make it here if needed!

**Comment by carletex** [comment]
Fixed on #27
